# generated by datamodel-codegen:
#   filename:  _schemas_v1_media-buy_build-creative-response_json.json

from __future__ import annotations

from enum import Enum
from typing import Annotated, Any, Literal, Optional

from pydantic import BaseModel, ConfigDict, Field


class Format(BaseModel):
    id: str
    name: str
    type: str


class OutputMode(Enum):
    manifest = "manifest"
    code = "code"


class SecurityRequirements(BaseModel):
    content_security_policy: Annotated[
        str, Field(description="Required CSP header for secure rendering")
    ]
    sandbox_attributes: Annotated[
        Optional[list[str]], Field(description="Required iframe sandbox attributes")
    ] = None
    xss_protection: Annotated[
        Literal["mandatory"], Field(description="XSS protection must be enabled")
    ]


class Creative(BaseModel):
    format: Annotated[
        Format, Field(description="Format specification used for this creative")
    ]
    output_mode: Annotated[
        OutputMode, Field(description="Type of creative output generated")
    ]
    security_requirements: Annotated[
        Optional[SecurityRequirements],
        Field(description="Security requirements for web-based creative code"),
    ] = None


class Type(Enum):
    variation = "variation"
    improvement = "improvement"
    format_adaptation = "format_adaptation"


class Suggestion(BaseModel):
    type: Type
    description: str
    prompt: str


class PerformanceInsights(BaseModel):
    predicted_ctr: Optional[float] = None
    engagement_factors: Optional[list[str]] = None
    optimization_opportunities: Optional[list[str]] = None


class Error(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    code: Annotated[str, Field(description="Error code for programmatic handling")]
    message: Annotated[str, Field(description="Human-readable error message")]
    field: Annotated[
        Optional[str],
        Field(
            description="Field path associated with the error (e.g., 'packages[0].targeting')"
        ),
    ] = None
    suggestion: Annotated[
        Optional[str], Field(description="Suggested fix for the error")
    ] = None
    retry_after: Annotated[
        Optional[float],
        Field(description="Seconds to wait before retrying the operation", ge=0.0),
    ] = None
    details: Annotated[
        Optional[Any], Field(description="Additional task-specific error details")
    ] = None


class BuildCreativeResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    context_id: Annotated[
        str, Field(description="Context identifier for iterative refinement")
    ]
    creative: Annotated[Creative, Field(description="Generated creative output")]
    suggestions: Annotated[
        Optional[list[Suggestion]],
        Field(description="Suggestions for creative improvement or variations"),
    ] = None
    performance_insights: Annotated[
        Optional[PerformanceInsights],
        Field(description="AI-generated insights about creative performance potential"),
    ] = None
    errors: Annotated[
        Optional[list[Error]], Field(description="Task-specific errors and warnings")
    ] = None
