# generated by datamodel-codegen:
#   filename:  _schemas_v1_index_json.json

from __future__ import annotations

from typing import Annotated, Any

from pydantic import Field, RootModel


class AdcpSchemaRegistryV1(RootModel[Any]):
    root: Annotated[
        Any,
        Field(
            description="Registry of all AdCP JSON schemas for validation and discovery",
            examples=[
                {
                    "language": "javascript",
                    "description": "JavaScript validation example",
                    "code": "const Ajv = require('ajv'); const ajv = new Ajv(); const schema = require('./schemas/v1/core/product.json'); const validate = ajv.compile(schema);",
                },
                {
                    "language": "python",
                    "description": "Python validation example",
                    "code": "import jsonschema; schema = {...}; jsonschema.validate(data, schema)",
                },
                {
                    "language": "java",
                    "description": "Java validation example",
                    "code": "// Use everit-org/json-schema or similar library",
                },
            ],
            title="AdCP Schema Registry v1",
        ),
    ]
