# generated by datamodel-codegen:
#   filename:  _schemas_v1_media-buy_package-request_json.json

from __future__ import annotations

from enum import Enum
from typing import Annotated, Literal, Optional, Union

from pydantic import AnyUrl, BaseModel, ConfigDict, Field, RootModel


class Pacing(Enum):
    even = "even"
    asap = "asap"
    front_loaded = "front_loaded"


class GeoCountryAnyOfItem(RootModel[str]):
    root: Annotated[str, Field(pattern="^[A-Z]{2}$")]


class FrequencyCap(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    suppress_minutes: Annotated[
        float, Field(description="Minutes to suppress after impression", ge=0.0)
    ]


class TargetingOverlay(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    geo_country_any_of: Annotated[
        Optional[list[GeoCountryAnyOfItem]],
        Field(
            description="Restrict delivery to specific countries (ISO codes). Use for regulatory compliance or RCT testing."
        ),
    ] = None
    geo_region_any_of: Annotated[
        Optional[list[str]],
        Field(
            description="Restrict delivery to specific regions/states. Use for regulatory compliance or RCT testing."
        ),
    ] = None
    geo_metro_any_of: Annotated[
        Optional[list[str]],
        Field(
            description="Restrict delivery to specific metro areas (DMA codes). Use for regulatory compliance or RCT testing."
        ),
    ] = None
    geo_postal_code_any_of: Annotated[
        Optional[list[str]],
        Field(
            description="Restrict delivery to specific postal/ZIP codes. Use for regulatory compliance or RCT testing."
        ),
    ] = None
    frequency_cap: Annotated[
        Optional[FrequencyCap],
        Field(
            description="Frequency capping settings for package-level application",
            title="Frequency Cap",
        ),
    ] = None


class FormatId(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    agent_url: Annotated[
        AnyUrl,
        Field(
            description="URL of the agent that defines this format (e.g., 'https://creatives.adcontextprotocol.org' for standard formats, or 'https://publisher.com/.well-known/adcp/sales' for custom formats)"
        ),
    ]
    id: Annotated[
        str,
        Field(
            description="Format identifier within the agent's namespace (e.g., 'display_300x250', 'video_standard_30s')",
            pattern="^[a-zA-Z0-9_-]+$",
        ),
    ]


class Assets(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    asset_type: Literal["image"]
    url: Annotated[AnyUrl, Field(description="URL to the image asset")]
    width: Annotated[
        Optional[int], Field(description="Image width in pixels", ge=1)
    ] = None
    height: Annotated[
        Optional[int], Field(description="Image height in pixels", ge=1)
    ] = None
    format: Annotated[
        Optional[str],
        Field(description="Image file format (jpg, png, gif, webp, etc.)"),
    ] = None
    alt_text: Annotated[
        Optional[str], Field(description="Alternative text for accessibility")
    ] = None


class Assets75(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    asset_type: Literal["video"]
    url: Annotated[AnyUrl, Field(description="URL to the video asset")]
    width: Annotated[
        Optional[int], Field(description="Video width in pixels", ge=1)
    ] = None
    height: Annotated[
        Optional[int], Field(description="Video height in pixels", ge=1)
    ] = None
    duration_ms: Annotated[
        Optional[int], Field(description="Video duration in milliseconds", ge=0)
    ] = None
    format: Annotated[
        Optional[str], Field(description="Video file format (mp4, webm, mov, etc.)")
    ] = None
    bitrate_kbps: Annotated[
        Optional[int], Field(description="Video bitrate in kilobits per second", ge=1)
    ] = None


class Assets76(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    asset_type: Literal["audio"]
    url: Annotated[AnyUrl, Field(description="URL to the audio asset")]
    duration_ms: Annotated[
        Optional[int], Field(description="Audio duration in milliseconds", ge=0)
    ] = None
    format: Annotated[
        Optional[str], Field(description="Audio file format (mp3, wav, aac, etc.)")
    ] = None
    bitrate_kbps: Annotated[
        Optional[int], Field(description="Audio bitrate in kilobits per second", ge=1)
    ] = None


class Assets77(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    asset_type: Literal["text"]
    content: Annotated[str, Field(description="Text content")]
    max_length: Annotated[
        Optional[int], Field(description="Maximum character length constraint", ge=1)
    ] = None
    language: Annotated[
        Optional[str], Field(description="Language code (e.g., 'en', 'es', 'fr')")
    ] = None


class Assets78(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    asset_type: Literal["html"]
    content: Annotated[str, Field(description="HTML content")]
    version: Annotated[
        Optional[str], Field(description="HTML version (e.g., 'HTML5')")
    ] = None


class Assets79(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    asset_type: Literal["css"]
    content: Annotated[str, Field(description="CSS content")]
    media: Annotated[
        Optional[str],
        Field(description="CSS media query context (e.g., 'screen', 'print')"),
    ] = None


class ModuleType(Enum):
    esm = "esm"
    commonjs = "commonjs"
    script = "script"


class Assets80(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    asset_type: Literal["javascript"]
    content: Annotated[str, Field(description="JavaScript content")]
    module_type: Annotated[
        Optional[ModuleType], Field(description="JavaScript module type")
    ] = None


class Colors(BaseModel):
    primary: Optional[str] = None
    secondary: Optional[str] = None
    accent: Optional[str] = None


class Assets81(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    asset_type: Literal["promoted_offerings"]
    url: Annotated[
        Optional[AnyUrl],
        Field(
            description="URL of the advertiser's brand or offering (e.g., https://retailer.com)"
        ),
    ] = None
    colors: Annotated[Optional[Colors], Field(description="Brand colors")] = None
    fonts: Annotated[Optional[list[str]], Field(description="Brand fonts")] = None
    tone: Annotated[Optional[str], Field(description="Brand tone/voice")] = None


class Assets82(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    asset_type: Literal["url"]
    url: Annotated[AnyUrl, Field(description="URL reference")]
    description: Annotated[
        Optional[str], Field(description="Description of what this URL points to")
    ] = None


class Input(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: Annotated[
        str, Field(description="Human-readable name for this preview variant")
    ]
    macros: Annotated[
        Optional[dict[str, str]],
        Field(description="Macro values to apply for this preview"),
    ] = None
    context_description: Annotated[
        Optional[str],
        Field(
            description="Natural language description of the context for AI-generated content"
        ),
    ] = None


class Creative(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    creative_id: Annotated[str, Field(description="Unique identifier for the creative")]
    name: Annotated[str, Field(description="Human-readable creative name")]
    format_id: Annotated[
        FormatId,
        Field(
            description="Structured format identifier with agent URL and format name",
            title="Format ID",
        ),
    ]
    assets: Annotated[
        dict[
            str,
            Union[
                Assets,
                Assets75,
                Assets76,
                Assets77,
                Assets78,
                Assets79,
                Assets80,
                Assets81,
                Assets82,
            ],
        ],
        Field(description="Assets required by the format, keyed by asset_role"),
    ]
    inputs: Annotated[
        Optional[list[Input]],
        Field(
            description="Preview contexts for generative formats - defines what scenarios to generate previews for"
        ),
    ] = None
    tags: Annotated[
        Optional[list[str]],
        Field(description="User-defined tags for organization and searchability"),
    ] = None
    approved: Annotated[
        Optional[bool],
        Field(
            description="For generative creatives: set to true to approve and finalize, false to request regeneration with updated assets/message. Omit for non-generative creatives."
        ),
    ] = None


class PackageRequest1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    buyer_ref: Annotated[
        str, Field(description="Buyer's reference identifier for this package")
    ]
    product_id: Annotated[
        str,
        Field(
            description="Product ID for this package (recommended - replaces deprecated products array)"
        ),
    ]
    products: Annotated[
        Optional[list[str]],
        Field(
            description="DEPRECATED: Use product_id instead. Array of product IDs - only first product will be used"
        ),
    ] = None
    format_ids: Annotated[
        Optional[list[str]],
        Field(
            description="Array of format IDs that will be used for this package - must be supported by the product. If omitted, defaults to all formats supported by the product.",
            min_length=1,
        ),
    ] = None
    budget: Annotated[
        float,
        Field(
            description="Budget allocation for this package in the media buy's currency",
            ge=0.0,
        ),
    ]
    pacing: Annotated[
        Optional[Pacing], Field(description="Budget pacing strategy", title="Pacing")
    ] = None
    pricing_option_id: Annotated[
        str,
        Field(
            description="ID of the selected pricing option from the product's pricing_options array"
        ),
    ]
    bid_price: Annotated[
        Optional[float],
        Field(
            description="Bid price for auction-based CPM pricing (required if using cpm-auction-option)",
            ge=0.0,
        ),
    ] = None
    targeting_overlay: Annotated[
        Optional[TargetingOverlay],
        Field(
            description="Optional geographic refinements for media buys. Most targeting should be expressed in the brief and handled by the publisher. These fields are primarily for geographic restrictions (RCT testing, regulatory compliance).",
            title="Targeting Overlay",
        ),
    ] = None
    creative_ids: Annotated[
        Optional[list[str]],
        Field(
            description="Creative IDs to assign to this package at creation time (references existing library creatives)"
        ),
    ] = None
    creatives: Annotated[
        Optional[list[Creative]],
        Field(
            description="Full creative objects to upload and assign to this package at creation time (alternative to creative_ids - creatives will be added to library). Supports both static and generative creatives.",
            max_length=100,
        ),
    ] = None


class TargetingOverlay7(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    geo_country_any_of: Annotated[
        Optional[list[GeoCountryAnyOfItem]],
        Field(
            description="Restrict delivery to specific countries (ISO codes). Use for regulatory compliance or RCT testing."
        ),
    ] = None
    geo_region_any_of: Annotated[
        Optional[list[str]],
        Field(
            description="Restrict delivery to specific regions/states. Use for regulatory compliance or RCT testing."
        ),
    ] = None
    geo_metro_any_of: Annotated[
        Optional[list[str]],
        Field(
            description="Restrict delivery to specific metro areas (DMA codes). Use for regulatory compliance or RCT testing."
        ),
    ] = None
    geo_postal_code_any_of: Annotated[
        Optional[list[str]],
        Field(
            description="Restrict delivery to specific postal/ZIP codes. Use for regulatory compliance or RCT testing."
        ),
    ] = None
    frequency_cap: Annotated[
        Optional[FrequencyCap],
        Field(
            description="Frequency capping settings for package-level application",
            title="Frequency Cap",
        ),
    ] = None


class Assets83(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    asset_type: Literal["image"]
    url: Annotated[AnyUrl, Field(description="URL to the image asset")]
    width: Annotated[
        Optional[int], Field(description="Image width in pixels", ge=1)
    ] = None
    height: Annotated[
        Optional[int], Field(description="Image height in pixels", ge=1)
    ] = None
    format: Annotated[
        Optional[str],
        Field(description="Image file format (jpg, png, gif, webp, etc.)"),
    ] = None
    alt_text: Annotated[
        Optional[str], Field(description="Alternative text for accessibility")
    ] = None


class Assets84(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    asset_type: Literal["video"]
    url: Annotated[AnyUrl, Field(description="URL to the video asset")]
    width: Annotated[
        Optional[int], Field(description="Video width in pixels", ge=1)
    ] = None
    height: Annotated[
        Optional[int], Field(description="Video height in pixels", ge=1)
    ] = None
    duration_ms: Annotated[
        Optional[int], Field(description="Video duration in milliseconds", ge=0)
    ] = None
    format: Annotated[
        Optional[str], Field(description="Video file format (mp4, webm, mov, etc.)")
    ] = None
    bitrate_kbps: Annotated[
        Optional[int], Field(description="Video bitrate in kilobits per second", ge=1)
    ] = None


class Assets85(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    asset_type: Literal["audio"]
    url: Annotated[AnyUrl, Field(description="URL to the audio asset")]
    duration_ms: Annotated[
        Optional[int], Field(description="Audio duration in milliseconds", ge=0)
    ] = None
    format: Annotated[
        Optional[str], Field(description="Audio file format (mp3, wav, aac, etc.)")
    ] = None
    bitrate_kbps: Annotated[
        Optional[int], Field(description="Audio bitrate in kilobits per second", ge=1)
    ] = None


class Assets86(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    asset_type: Literal["text"]
    content: Annotated[str, Field(description="Text content")]
    max_length: Annotated[
        Optional[int], Field(description="Maximum character length constraint", ge=1)
    ] = None
    language: Annotated[
        Optional[str], Field(description="Language code (e.g., 'en', 'es', 'fr')")
    ] = None


class Assets87(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    asset_type: Literal["html"]
    content: Annotated[str, Field(description="HTML content")]
    version: Annotated[
        Optional[str], Field(description="HTML version (e.g., 'HTML5')")
    ] = None


class Assets88(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    asset_type: Literal["css"]
    content: Annotated[str, Field(description="CSS content")]
    media: Annotated[
        Optional[str],
        Field(description="CSS media query context (e.g., 'screen', 'print')"),
    ] = None


class Assets89(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    asset_type: Literal["javascript"]
    content: Annotated[str, Field(description="JavaScript content")]
    module_type: Annotated[
        Optional[ModuleType], Field(description="JavaScript module type")
    ] = None


class Assets90(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    asset_type: Literal["promoted_offerings"]
    url: Annotated[
        Optional[AnyUrl],
        Field(
            description="URL of the advertiser's brand or offering (e.g., https://retailer.com)"
        ),
    ] = None
    colors: Annotated[Optional[Colors], Field(description="Brand colors")] = None
    fonts: Annotated[Optional[list[str]], Field(description="Brand fonts")] = None
    tone: Annotated[Optional[str], Field(description="Brand tone/voice")] = None


class Assets91(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    asset_type: Literal["url"]
    url: Annotated[AnyUrl, Field(description="URL reference")]
    description: Annotated[
        Optional[str], Field(description="Description of what this URL points to")
    ] = None


class Creative7(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    creative_id: Annotated[str, Field(description="Unique identifier for the creative")]
    name: Annotated[str, Field(description="Human-readable creative name")]
    format_id: Annotated[
        FormatId,
        Field(
            description="Structured format identifier with agent URL and format name",
            title="Format ID",
        ),
    ]
    assets: Annotated[
        dict[
            str,
            Union[
                Assets83,
                Assets84,
                Assets85,
                Assets86,
                Assets87,
                Assets88,
                Assets89,
                Assets90,
                Assets91,
            ],
        ],
        Field(description="Assets required by the format, keyed by asset_role"),
    ]
    inputs: Annotated[
        Optional[list[Input]],
        Field(
            description="Preview contexts for generative formats - defines what scenarios to generate previews for"
        ),
    ] = None
    tags: Annotated[
        Optional[list[str]],
        Field(description="User-defined tags for organization and searchability"),
    ] = None
    approved: Annotated[
        Optional[bool],
        Field(
            description="For generative creatives: set to true to approve and finalize, false to request regeneration with updated assets/message. Omit for non-generative creatives."
        ),
    ] = None


class PackageRequest2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    buyer_ref: Annotated[
        str, Field(description="Buyer's reference identifier for this package")
    ]
    product_id: Annotated[
        Optional[str],
        Field(
            description="Product ID for this package (recommended - replaces deprecated products array)"
        ),
    ] = None
    products: Annotated[
        list[str],
        Field(
            description="DEPRECATED: Use product_id instead. Array of product IDs - only first product will be used"
        ),
    ]
    format_ids: Annotated[
        Optional[list[str]],
        Field(
            description="Array of format IDs that will be used for this package - must be supported by the product. If omitted, defaults to all formats supported by the product.",
            min_length=1,
        ),
    ] = None
    budget: Annotated[
        float,
        Field(
            description="Budget allocation for this package in the media buy's currency",
            ge=0.0,
        ),
    ]
    pacing: Annotated[
        Optional[Pacing], Field(description="Budget pacing strategy", title="Pacing")
    ] = None
    pricing_option_id: Annotated[
        str,
        Field(
            description="ID of the selected pricing option from the product's pricing_options array"
        ),
    ]
    bid_price: Annotated[
        Optional[float],
        Field(
            description="Bid price for auction-based CPM pricing (required if using cpm-auction-option)",
            ge=0.0,
        ),
    ] = None
    targeting_overlay: Annotated[
        Optional[TargetingOverlay7],
        Field(
            description="Optional geographic refinements for media buys. Most targeting should be expressed in the brief and handled by the publisher. These fields are primarily for geographic restrictions (RCT testing, regulatory compliance).",
            title="Targeting Overlay",
        ),
    ] = None
    creative_ids: Annotated[
        Optional[list[str]],
        Field(
            description="Creative IDs to assign to this package at creation time (references existing library creatives)"
        ),
    ] = None
    creatives: Annotated[
        Optional[list[Creative7]],
        Field(
            description="Full creative objects to upload and assign to this package at creation time (alternative to creative_ids - creatives will be added to library). Supports both static and generative creatives.",
            max_length=100,
        ),
    ] = None


class PackageRequest(RootModel[Union[PackageRequest1, PackageRequest2]]):
    root: Annotated[
        Union[PackageRequest1, PackageRequest2],
        Field(
            description="Package configuration for media buy creation",
            title="Package Request",
        ),
    ]
