# generated by datamodel-codegen:
#   filename:  _schemas_v1_creative_preview-creative-response_json.json

from __future__ import annotations

from enum import Enum
from typing import Annotated, Any, Literal, Optional, Union

from pydantic import AnyUrl, AwareDatetime, BaseModel, ConfigDict, Field, RootModel


class OutputFormat(Enum):
    url = "url"
    html = "html"
    both = "both"


class Dimensions(BaseModel):
    width: Annotated[float, Field(ge=0.0)]
    height: Annotated[float, Field(ge=0.0)]


class Embedding(BaseModel):
    recommended_sandbox: Annotated[
        Optional[str],
        Field(
            description="Recommended iframe sandbox attribute value (e.g., 'allow-scripts allow-same-origin')"
        ),
    ] = None
    requires_https: Annotated[
        Optional[bool],
        Field(description="Whether this output requires HTTPS for secure embedding"),
    ] = None
    supports_fullscreen: Annotated[
        Optional[bool],
        Field(description="Whether this output supports fullscreen mode"),
    ] = None
    csp_policy: Annotated[
        Optional[str],
        Field(description="Content Security Policy requirements for embedding"),
    ] = None


class Render(BaseModel):
    render_id: Annotated[
        str,
        Field(
            description="Unique identifier for this rendered piece within the variant"
        ),
    ]
    output_format: Annotated[
        OutputFormat,
        Field(
            description="Discriminator field indicating which preview format(s) are provided. 'url' = preview_url only, 'html' = preview_html only, 'both' = both preview_url and preview_html."
        ),
    ]
    preview_url: Annotated[
        Optional[AnyUrl],
        Field(
            description="URL to an HTML page that renders this piece. Can be embedded in an iframe. Present when output_format is 'url' or 'both'."
        ),
    ] = None
    preview_html: Annotated[
        Optional[str],
        Field(
            description="Raw HTML for this rendered piece. Can be embedded directly in the page without iframe. Present when output_format is 'html' or 'both'. Security warning: Only use with trusted creative agents as this bypasses iframe sandboxing."
        ),
    ] = None
    role: Annotated[
        str,
        Field(
            description="Semantic role of this rendered piece. Use 'primary' for main content, 'companion' for associated banners, descriptive strings for device variants or custom roles."
        ),
    ]
    dimensions: Annotated[
        Optional[Dimensions],
        Field(
            description="Dimensions for this rendered piece. For companion ads with multiple sizes, this specifies which size this piece is."
        ),
    ] = None
    embedding: Annotated[
        Optional[Embedding],
        Field(
            description="Optional security and embedding metadata for safe iframe integration"
        ),
    ] = None


class Input(BaseModel):
    name: Annotated[str, Field(description="Human-readable name for this variant")]
    macros: Annotated[
        Optional[dict[str, str]],
        Field(description="Macro values applied to this variant"),
    ] = None
    context_description: Annotated[
        Optional[str], Field(description="Context description applied to this variant")
    ] = None


class Preview(BaseModel):
    preview_id: Annotated[
        str, Field(description="Unique identifier for this preview variant")
    ]
    renders: Annotated[
        list[Render],
        Field(
            description="Array of rendered pieces for this preview variant. Most formats render as a single piece. Companion ad formats (video + banner), multi-placement formats, and adaptive formats render as multiple pieces.",
            min_length=1,
        ),
    ]
    input: Annotated[
        Input,
        Field(
            description="The input parameters that generated this preview variant. Echoes back the request input or shows defaults used."
        ),
    ]


class PreviewCreativeResponse1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    previews: Annotated[
        list[Preview],
        Field(
            description="Array of preview variants. Each preview corresponds to an input set from the request. If no inputs were provided, returns a single default preview.",
            min_length=1,
        ),
    ]
    interactive_url: Annotated[
        Optional[AnyUrl],
        Field(
            description="Optional URL to an interactive testing page that shows all preview variants with controls to switch between them, modify macro values, and test different scenarios."
        ),
    ] = None
    expires_at: Annotated[
        AwareDatetime, Field(description="ISO 8601 timestamp when preview links expire")
    ]


class Embedding1(BaseModel):
    recommended_sandbox: Optional[str] = None
    requires_https: Optional[bool] = None
    supports_fullscreen: Optional[bool] = None
    csp_policy: Optional[str] = None


class Render3(BaseModel):
    render_id: str
    output_format: Annotated[
        OutputFormat,
        Field(
            description="Discriminator field indicating which preview format(s) are provided. 'url' = preview_url only, 'html' = preview_html only, 'both' = both preview_url and preview_html."
        ),
    ]
    preview_url: Annotated[
        Optional[AnyUrl],
        Field(
            description="URL to iframe-embeddable HTML page. Present when output_format is 'url' or 'both'."
        ),
    ] = None
    preview_html: Annotated[
        Optional[str],
        Field(
            description="Raw HTML for direct embedding. Present when output_format is 'html' or 'both'. Security: Only use with trusted agents."
        ),
    ] = None
    role: str
    dimensions: Optional[Dimensions] = None
    embedding: Optional[Embedding1] = None


class Input4(BaseModel):
    name: str
    macros: Optional[dict[str, str]] = None
    context_description: Optional[str] = None


class Preview1(BaseModel):
    preview_id: str
    renders: Annotated[list[Render3], Field(min_length=1)]
    input: Input4


class Response(BaseModel):
    previews: Annotated[
        list[Preview1],
        Field(description="Array of preview variants for this creative", min_length=1),
    ]
    interactive_url: Optional[AnyUrl] = None
    expires_at: AwareDatetime


class Error(BaseModel):
    code: Annotated[
        str,
        Field(
            description="Error code (e.g., 'invalid_manifest', 'unsupported_format', 'missing_assets')"
        ),
    ]
    message: Annotated[str, Field(description="Human-readable error message")]
    details: Annotated[
        Optional[dict[str, Any]], Field(description="Additional error context")
    ] = None


class Results(BaseModel):
    success: Annotated[
        Literal[True], Field(description="Whether this preview request succeeded")
    ]
    response: Annotated[
        Response, Field(description="Preview response for successful requests")
    ]
    error: Annotated[
        Optional[Error], Field(description="Error information for failed requests")
    ] = None


Render4 = Render3


class Preview2(BaseModel):
    preview_id: str
    renders: Annotated[list[Render4], Field(min_length=1)]
    input: Input4


class Response1(BaseModel):
    previews: Annotated[
        list[Preview2],
        Field(description="Array of preview variants for this creative", min_length=1),
    ]
    interactive_url: Optional[AnyUrl] = None
    expires_at: AwareDatetime


class Results1(BaseModel):
    success: Annotated[
        Literal[False], Field(description="Whether this preview request succeeded")
    ]
    response: Annotated[
        Optional[Response1],
        Field(description="Preview response for successful requests"),
    ] = None
    error: Annotated[Error, Field(description="Error information for failed requests")]


class PreviewCreativeResponse2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    results: Annotated[
        list[Union[Results, Results1]],
        Field(
            description="Array of preview results corresponding to each request in the same order. results[0] is the result for requests[0], results[1] for requests[1], etc. Order is guaranteed even when some requests fail. Each result contains either a successful preview response or an error.",
            min_length=1,
        ),
    ]


class PreviewCreativeResponse(
    RootModel[Union[PreviewCreativeResponse1, PreviewCreativeResponse2]]
):
    root: Annotated[
        Union[PreviewCreativeResponse1, PreviewCreativeResponse2],
        Field(
            description="Response containing preview links for one or more creatives. Format matches the request: single preview response for single requests, batch results for batch requests.",
            title="Preview Creative Response",
        ),
    ]
