# generated by datamodel-codegen:
#   filename:  _schemas_v1_signals_activate-signal-response_json.json

from __future__ import annotations

from enum import Enum
from typing import Annotated, Any, Optional

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class Status(Enum):
    submitted = "submitted"
    working = "working"
    input_required = "input-required"
    completed = "completed"
    canceled = "canceled"
    failed = "failed"
    rejected = "rejected"
    auth_required = "auth-required"
    unknown = "unknown"


class Error(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    code: Annotated[str, Field(description="Error code for programmatic handling")]
    message: Annotated[str, Field(description="Human-readable error message")]
    field: Annotated[
        Optional[str],
        Field(
            description="Field path associated with the error (e.g., 'packages[0].targeting')"
        ),
    ] = None
    suggestion: Annotated[
        Optional[str], Field(description="Suggested fix for the error")
    ] = None
    retry_after: Annotated[
        Optional[float],
        Field(description="Seconds to wait before retrying the operation", ge=0.0),
    ] = None
    details: Annotated[
        Optional[Any], Field(description="Additional task-specific error details")
    ] = None


class ActivateSignalResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    message: Annotated[
        str, Field(description="Human-readable summary of the activation status")
    ]
    context_id: Annotated[
        str, Field(description="Session continuity identifier for tracking progress")
    ]
    task_id: Annotated[
        str, Field(description="Unique identifier for tracking the activation")
    ]
    status: Annotated[
        Status,
        Field(
            description="Standardized task status values based on A2A TaskState enum. Indicates the current state of any AdCP operation.",
            title="Task Status",
        ),
    ]
    decisioning_platform_segment_id: Annotated[
        Optional[str],
        Field(description="The platform-specific ID to use once activated"),
    ] = None
    estimated_activation_duration_minutes: Annotated[
        Optional[float],
        Field(description="Estimated time to complete (optional)", ge=0.0),
    ] = None
    deployed_at: Annotated[
        Optional[AwareDatetime],
        Field(description="Timestamp when activation completed (optional)"),
    ] = None
    errors: Annotated[
        Optional[list[Error]],
        Field(
            description="Task-specific errors and warnings (e.g., activation failures, platform issues)"
        ),
    ] = None
