# generated by datamodel-codegen:
#   filename:  _schemas_v1_core_format_json.json
#   timestamp: 2025-10-15T08:50:14+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Optional, Union

from typing import Annotated

from pydantic import AnyUrl, BaseModel, ConfigDict, Field


class Type(Enum):
    audio = 'audio'
    video = 'video'
    display = 'display'
    native = 'native'
    dooh = 'dooh'
    rich_media = 'rich_media'
    universal = 'universal'


class AssetType(Enum):
    image = 'image'
    video = 'video'
    audio = 'audio'
    text = 'text'
    html = 'html'
    javascript = 'javascript'
    url = 'url'
    brand_manifest = 'brand_manifest'


class AssetsRequired(BaseModel):
    asset_id: str = Field(..., description='Identifier for this asset in the format')
    asset_type: AssetType = Field(..., description='Type of asset')
    asset_role: Optional[str] = Field(
        None,
        description="Purpose of this asset (e.g., 'hero_image', 'logo', 'headline', 'cta_button')",
    )
    required: Optional[bool] = Field(None, description='Whether this asset is required')
    requirements: Optional[Dict[str, Any]] = Field(
        None,
        description='Technical requirements for this asset (dimensions, file size, duration, etc.)',
    )


class Repeatable(Enum):
    boolean_True = True


class Asset(BaseModel):
    asset_id: str = Field(..., description='Identifier for this asset within the group')
    asset_type: AssetType = Field(..., description='Type of asset')
    asset_role: Optional[str] = Field(None, description='Purpose of this asset')
    required: Optional[bool] = Field(
        None, description='Whether this asset is required in each repetition'
    )
    requirements: Optional[Dict[str, Any]] = Field(
        None, description='Technical requirements for this asset'
    )


class AssetsRequired1(BaseModel):
    asset_group_id: str = Field(
        ...,
        description="Identifier for this asset group (e.g., 'product', 'slide', 'card')",
    )
    repeatable: Repeatable = Field(
        ..., description='Indicates this is a repeatable asset group'
    )
    min_count: Annotated[int, Field(ge=1)] = Field(
        ..., description='Minimum number of repetitions required'
    )
    max_count: Annotated[int, Field(ge=1)] = Field(
        ..., description='Maximum number of repetitions allowed'
    )
    assets: List[Asset] = Field(
        ..., description='Assets within each repetition of this group'
    )


class Responsive(BaseModel):
    width: bool
    height: bool


class Unit(Enum):
    px = 'px'
    dp = 'dp'
    inches = 'inches'
    cm = 'cm'


class Dimensions(BaseModel):
    width: Optional[Annotated[float, Field(ge=0.0)]] = None
    height: Optional[Annotated[float, Field(ge=0.0)]] = None
    min_width: Optional[Annotated[float, Field(ge=0.0)]] = None
    min_height: Optional[Annotated[float, Field(ge=0.0)]] = None
    max_width: Optional[Annotated[float, Field(ge=0.0)]] = None
    max_height: Optional[Annotated[float, Field(ge=0.0)]] = None
    responsive: Optional[Responsive] = None
    aspect_ratio: Optional[Annotated[str, Field(pattern=r'^\d+:\d+$')]] = None
    unit: Unit


class Render(BaseModel):
    role: str = Field(..., description='Semantic role of this rendered piece')
    dimensions: Dimensions


class Format(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    format_id: str = Field(..., description='Unique identifier for the format')
    agent_url: Optional[AnyUrl] = Field(
        None,
        description="Base URL of the agent that provides this format (authoritative source). E.g., 'https://reference.adcp.org', 'https://dco.example.com'",
    )
    name: str = Field(..., description='Human-readable format name')
    description: Optional[str] = Field(
        None,
        description='Plain text explanation of what this format does and what assets it requires',
    )
    preview_image: Optional[AnyUrl] = Field(
        None, description='Optional preview image URL for format browsing/discovery UI'
    )
    example_url: Optional[AnyUrl] = Field(
        None,
        description='Optional URL to showcase page with examples and interactive demos of this format',
    )
    type: Type = Field(
        ...,
        description='Media type of this format - determines rendering method and asset requirements',
    )
    requirements: Optional[Dict[str, Any]] = Field(
        None,
        description='Technical specifications for this format (e.g., dimensions, duration, file size limits, codecs)',
    )
    assets_required: Optional[List[Union[AssetsRequired, AssetsRequired1]]] = Field(
        None,
        description='Array of required assets or asset groups for this format. Can contain individual assets or repeatable asset sequences (e.g., carousel products, slideshow frames).',
    )
    delivery: Optional[Dict[str, Any]] = Field(
        None,
        description='Delivery method specifications (e.g., hosted, VAST, third-party tags)',
    )
    supported_macros: Optional[List[str]] = Field(
        None,
        description='List of universal macros supported by this format (e.g., MEDIA_BUY_ID, CACHEBUSTER, DEVICE_ID). Used for validation and developer tooling.',
    )
    output_format_ids: Optional[List[str]] = Field(
        None,
        description='For generative formats: array of format IDs that this format can generate. When a format accepts inputs like brand_manifest and message, this specifies what concrete output formats can be produced (e.g., a generative banner format might output standard image banner formats).',
    )
    renders: Optional[List[Render]] = Field(
        None,
        description='Specification of rendered pieces for this format',
        min_length=1,
    )
